apiVersion: v1
kind: ServiceAccount
metadata:
    name: buildbot

---

apiVersion: v1
kind: Secret
metadata:
  name: buildbot
  annotations:
    kubernetes.io/service-account.name: buildbot
type: kubernetes.io/service-account-token
